import MaybeShowNavbar from "@/app/components/MaybeShowNavbar/MaybeShowNavbar";
import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MaybeShowNavbar>
          <Navbar />
        </MaybeShowNavbar>
        {children}
      </body>
    </html>
  );
}
