"use client";

const Footer = () => {
    return(
        <>
        <div>
            <h2>Im footer Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos eos eligendi nemo, corporis accusantium voluptate mollitia aspernatur quidem dicta nesciunt est facilis minima corrupti reiciendis pariatur placeat recusandae magni neque? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad eius at qui blanditiis repellendus alias, exercitationem voluptatum saepe, accusamus suscipit tempora autem esse pariatur reiciendis. Ipsa sequi minima quis exercitationem.
            Nesciunt nihil voluptatibus quas, maxime nemo dolor eveniet, quae nostrum eum molestias veritatis sed minima quo at dolorum aliquid quos rerum vitae! Aliquid totam magni quibusdam sint similique voluptate accusantium?
            Nulla suscipit nesciunt consectetur fuga beatae totam voluptates autem illo officiis est quisquam, magni nobis, consequuntur culpa esse libero ut reiciendis omnis voluptas eaque dolor incidunt saepe. Sed, fugit esse!
            Possimus, facere? Eius odio ipsam animi aliquam libero perspiciatis maxime sapiente tempore voluptate nesciunt ipsa adipisci fugiat, aut veritatis quia nemo repellat nisi aliquid inventore sed totam corporis voluptatem et.
            Nostrum quas ex cum asperiores consectetur debitis deleniti, repellendus perspiciatis sapiente est dolores neque voluptatum provident ratione quasi libero quos aliquid, facilis vel laborum hic nulla. Eius nam sint qui!
            Sit adipisci deserunt doloremque iure atque deleniti maiores numquam dolores rerum hic rem ullam cumque similique accusamus quod consequatur dignissimos aliquam reprehenderit magnam, distinctio tempore doloribus. Eaque dolore soluta provident.
            Odio, molestias quos. Corporis dolor iusto obcaecati beatae facere neque molestias, voluptatum soluta facilis tenetur pariatur esse quis natus repellat illo accusamus ullam, adipisci iste eius numquam unde, nihil at.
            Ipsum sit voluptatem labore quae sunt. Autem, mollitia magnam nesciunt rerum amet quas vitae ex. Repudiandae nisi aliquam nesciunt eos. Cupiditate assumenda dignissimos accusantium perspiciatis porro nesciunt magni culpa quo?
            Ex dolorem numquam praesentium consectetur reprehenderit provident vel pariatur maxime quisquam velit exercitationem, deserunt placeat architecto nulla eum aut explicabo reiciendis ab. Earum accusamus officia corporis quibusdam omnis quisquam cum?
            Ut dicta suscipit et eius atque. Eligendi natus corrupti autem distinctio sit aut, iure, id atque dolores exercitationem cumque dignissimos quisquam laborum itaque perferendis illo quod ipsum dolorem ad ullam.
            Modi pariatur ea quibusdam, qui molestias nobis. Nulla ut error laborum dolores non aperiam! Repellat perspiciatis quam, distinctio quia aspernatur nam iure sit natus rem maxime ullam molestiae ratione suscipit.
            Quo, fugit necessitatibus? Commodi, earum porro! Inventore iusto illum porro sapiente earum quos molestiae impedit fuga, unde minima debitis atque, velit quaerat maiores maxime explicabo at fugit quo dignissimos veniam?
            Corrupti possimus quam fugit. Odit, rerum eveniet similique ab voluptatem quisquam, illum modi facere commodi totam quae earum dolor quibusdam non! Cumque, fugiat inventore est blanditiis obcaecati ex rerum ut.
            Accusantium iste ipsam tempore inventore molestiae, deserunt culpa animi ab corrupti rerum consectetur aut aliquid iusto perspiciatis pariatur temporibus omnis, dolor praesentium dolore. Sed quam exercitationem repellendus. Dolores, delectus dolorum?
            Nisi soluta cumque corrupti, eius sit autem recusandae debitis, optio nam dolores neque! Vitae, maiores quo blanditiis consectetur vero commodi quod praesentium aperiam nihil illum incidunt consequatur ad similique dignissimos?
            Quas perspiciatis repellendus distinctio perferendis corrupti possimus, placeat cum optio facere, recusandae saepe, impedit qui ipsa nam temporibus! Laboriosam illum veritatis dignissimos quisquam quidem aliquid ipsum placeat eos quis non?
            Repellat, illum! Id quisquam dolorem tempore ab placeat vero similique maxime ad, corporis odit eveniet blanditiis natus et ex, molestiae debitis soluta rerum, dolore eius fugiat impedit ipsum! Quas, possimus.
            Facilis ipsum maiores asperiores ab repellendus amet cumque accusamus ut optio libero inventore omnis aspernatur veritatis atque odit adipisci quam, at, sunt quasi eum quaerat. Nam accusamus harum voluptates. Natus.
            Dicta culpa natus, impedit error vitae voluptatum iusto fugiat beatae harum? Rerum, autem quibusdam! Voluptatum qui, eveniet provident quisquam asperiores assumenda placeat libero recusandae a pariatur in. Aliquid, corporis distinctio.
            Nihil laborum officia mollitia labore animi in laboriosam ducimus dignissimos iusto? Illo praesentium neque repudiandae quibusdam nostrum quaerat molestias repellendus, iusto, accusantium hic nam quod blanditiis ipsa cumque itaque! Aperiam.
            Commodi saepe vel recusandae placeat similique voluptate assumenda cumque maiores necessitatibus accusantium enim deleniti quasi quas voluptas soluta architecto velit repellat eaque, nesciunt blanditiis error ab esse corrupti! Laboriosam, beatae.
            Adipisci vitae officiis earum excepturi est. Ad praesentium eum nemo, velit omnis consequatur, quisquam dolorum ducimus molestiae explicabo neque minima tenetur et consectetur sint nam reprehenderit ratione laborum eius error!
            Dolores aperiam quos ex quod tempora at quibusdam, voluptatem excepturi rerum porro! Autem perferendis, laudantium itaque exercitationem facilis veniam! Voluptas illo quo expedita voluptate necessitatibus laboriosam molestias ratione odit reiciendis.
            Possimus, deserunt dicta. Sed eum perferendis iure, eveniet quisquam praesentium quam repudiandae quis reiciendis quod facere sint animi, hic laboriosam, a repellat nam deleniti. Repudiandae doloremque fuga veniam nesciunt reiciendis!
            Laborum nulla dignissimos et expedita, voluptatibus rerum perferendis, ipsam accusamus cumque, nam unde mollitia voluptas maiores ipsum blanditiis! Atque nostrum id nobis provident. Tempore dolorem omnis quasi distinctio itaque tempora.
            Ad tenetur vel non beatae iste in facilis fuga esse dolorem debitis nemo fugit deleniti officiis quia perspiciatis saepe neque perferendis, doloremque qui id labore ratione harum culpa? Omnis, illo?
            Exercitationem deserunt maiores reiciendis accusamus unde nesciunt voluptates! Quisquam maiores minus fugit placeat porro earum mollitia excepturi ratione tenetur reiciendis dolore saepe, accusantium unde tempore dolores laudantium repellendus eligendi beatae.
            Incidunt molestias unde placeat nostrum quasi sunt eaque quae quod impedit optio ducimus, autem facere molestiae maiores consectetur? Ipsum quam vitae possimus magnam nam cum dignissimos veniam esse tenetur soluta.
            Facilis, tempora earum? Fuga dolorem eius unde cupiditate. Fugit rem iste voluptas cum cupiditate nam quod natus maxime vel doloribus. Impedit molestiae est optio aut, minima dolor aperiam consequuntur quaerat.
            Natus voluptate eveniet quo molestiae, minima eius magnam cumque sunt voluptas, et exercitationem quia cupiditate, saepe totam delectus nam dicta. Animi nobis fugit excepturi earum sed esse. Non, suscipit distinctio!
            Tenetur incidunt totam non nobis debitis laudantium perspiciatis voluptate nulla magni. Iste id eaque, esse eveniet, vero ullam iusto repellat impedit voluptatum tempore dolore quis. Quas delectus at placeat deleniti.
            Deserunt reiciendis nesciunt voluptatem aliquid enim animi? Odio quaerat voluptatem ratione tenetur corrupti cupiditate, nam iusto fugit, ullam, enim quod magni praesentium architecto odit asperiores hic ipsam provident ut harum.
            Error cumque laudantium voluptate minus, non dolorum reiciendis recusandae nulla sequi nemo veniam, hic, nesciunt magni! Voluptas iusto aperiam, eius eligendi aliquid dolore facere saepe ipsam, totam, consequuntur repudiandae aut.
            Officiis obcaecati odio incidunt sequi, illo exercitationem itaque dolorem expedita necessitatibus quidem autem. Labore rerum error illum dolore vitae pariatur veritatis eveniet? Quia ex consequuntur accusamus molestias nobis tempora modi!
            Earum minus omnis deserunt veniam odit. Sapiente dolorum nemo praesentium enim debitis minus esse aspernatur numquam assumenda, at cumque tempore dignissimos suscipit voluptatem neque dolorem quae, architecto tenetur eum nihil!
            Dolor illo dignissimos quasi similique est dolorum dolores quis ducimus dicta. Nihil temporibus dignissimos illum porro eveniet iusto velit aspernatur expedita, officiis quibusdam mollitia enim odio. Neque rerum eligendi pariatur?
            Quis nihil rem expedita enim sed iste temporibus, veniam officia! Nesciunt consequuntur dolor deserunt similique, quas a, debitis laboriosam necessitatibus, quam perspiciatis ipsa quasi veritatis tempore dolores. Corrupti, tenetur distinctio.
            Recusandae eos, porro qui, id expedita inventore minima laboriosam impedit distinctio animi esse fugiat harum placeat nemo rem a. Veniam ratione voluptas numquam accusamus fugit maiores laudantium corrupti similique deserunt.
            Esse laborum qui ipsa eum voluptates iste, error architecto magni quos iusto quae facilis praesentium odit laboriosam culpa quaerat quas. Architecto explicabo ut tempore sequi reprehenderit, deleniti ipsam quam saepe!
            A quia enim possimus architecto ad velit veniam asperiores assumenda aspernatur laudantium voluptas exercitationem officiis, itaque harum deserunt recusandae debitis. Porro nihil recusandae possimus quod reiciendis quam praesentium, minima necessitatibus.
            Distinctio nesciunt quia aut asperiores soluta amet vero eum, et quos nisi molestias accusantium voluptatum, in dignissimos. Sit laboriosam accusamus accusantium facere facilis voluptas assumenda! Ab libero possimus unde dignissimos.
            Totam adipisci, error est illum dolorem ipsa expedita velit molestias nemo inventore at repellat vero earum non quis nobis! Quis reiciendis optio aperiam aliquid, nulla numquam dolore corporis quas? Veniam.
            Delectus excepturi ab, maxime quam repellat libero officiis et amet sequi deserunt sit. Non magnam reiciendis illum. Perspiciatis doloribus alias ea porro repellendus a ex, tempora eos deleniti consequuntur atque.
            Placeat voluptatum nostrum animi in fuga. Ab aperiam quisquam, minima doloribus, alias vel repellendus consectetur non quae, repudiandae pariatur doloremque iusto ut? Debitis soluta maiores voluptas reiciendis molestiae eligendi neque?
            Magni quam sunt asperiores? Eius ex ducimus, deserunt provident reiciendis neque facilis ullam animi dolore vitae tenetur exercitationem nostrum, dolor veniam amet consectetur est quibusdam vel cupiditate eveniet incidunt aut.
            Optio ipsam eligendi vitae sit eos. Corrupti accusantium fugiat aperiam! Quaerat accusamus nobis ad doloremque accusantium! Veritatis dolorem, saepe assumenda unde molestias sit fuga porro iure qui, atque necessitatibus autem!
            Beatae eligendi, veritatis quis id quidem temporibus harum impedit repudiandae corrupti molestias sequi? Eveniet quod, animi voluptatem aliquid voluptate ipsum doloremque dicta officiis dolores qui earum non, atque culpa quos.
            Explicabo accusantium neque earum, harum assumenda modi, pariatur fugit laborum ratione expedita atque nesciunt iure! Accusantium cum atque libero laudantium aut at. Culpa, illo suscipit ipsa rem quam a blanditiis.
            Expedita, modi. Aspernatur unde voluptate quidem ut voluptates officiis earum blanditiis molestiae modi doloremque! Maiores repellendus, eos quis exercitationem rem impedit fugiat quos! Mollitia autem est ex blanditiis fuga nemo.
            Corporis fugit asperiores obcaecati pariatur dolore, perspiciatis ipsa deleniti laudantium nobis velit. Maxime illum distinctio nemo voluptates totam autem modi cum quidem amet. Minima assumenda accusamus eaque consectetur, repudiandae voluptate?
            Blanditiis praesentium ab totam. Quia quae doloremque nesciunt aut dolor distinctio non similique, sint nemo asperiores at. A doloribus ea, sed natus in, nesciunt totam et dolores voluptates, laudantium laboriosam.
            Corporis dolores aliquam exercitationem ea? Illum excepturi cum quisquam optio vitae accusantium dolorum eaque rerum delectus laboriosam eum reprehenderit repellat obcaecati repellendus cupiditate, possimus ullam! Quia cupiditate enim repellat nulla.
            Natus deserunt necessitatibus nisi. Maxime laboriosam aut veritatis! Obcaecati dolor accusamus odio nemo quos eaque aperiam, laudantium iste rerum harum facere doloremque, hic, sit nobis ipsum iusto ex quam recusandae.
            Earum fugiat recusandae, error illo reiciendis quisquam accusantium, sit quos veniam laudantium numquam. Voluptatibus quidem suscipit quam iure dicta rem cumque error, tempore commodi laborum veritatis quia, fuga exercitationem! Obcaecati.
            Repellendus consequuntur quidem placeat magni, expedita iure. Non rem tempora fugit reiciendis quod eveniet, corporis nemo ipsam molestias eligendi deserunt ea amet vitae culpa accusamus sit est atque debitis voluptates?
            Ipsum natus eveniet eius unde nihil dolorum, qui cumque odio consectetur in tempore eaque quos, eos iure et aperiam soluta doloribus necessitatibus ab, ex sequi quaerat! Praesentium exercitationem amet dolorum!
            Pariatur quas ut harum culpa impedit ipsum quaerat minus, commodi distinctio neque ea nemo accusamus beatae quibusdam explicabo voluptates deserunt ullam quos ab earum illo quasi! Pariatur velit fuga quidem?
            Sed illum, architecto voluptatum harum numquam, ipsam ea quibusdam eligendi natus eveniet sint! Optio nostrum ratione suscipit sint repellat libero, dolorem temporibus vitae necessitatibus inventore odio illo eaque? Temporibus, quia.
            Dolore excepturi veniam voluptate itaque sed incidunt architecto nostrum accusamus, sunt odio qui beatae tempora veritatis quisquam eaque ea commodi quis ad porro exercitationem, voluptates, sapiente ut? Quam, maxime ullam!
            Optio totam omnis placeat mollitia dolorem nesciunt expedita beatae aut voluptas repellat ea architecto facilis neque hic porro excepturi repudiandae officiis obcaecati quas commodi vitae, fugiat quis officia. Labore, placeat?
            Repellendus doloremque eum dicta placeat facilis laboriosam harum sapiente et? Optio magnam quas sit corrupti omnis veritatis commodi iste expedita repudiandae. Sapiente labore ea quia distinctio quas, alias doloribus accusantium?
            Illo officiis placeat ratione, soluta voluptates architecto ea excepturi cum ipsum vel culpa voluptate sint, illum velit iure expedita cumque minus in? Perspiciatis iure corrupti alias rerum quibusdam modi nihil?
            Sed, doloribus quis nemo repellat minus cumque atque quidem amet porro similique obcaecati ullam, at nesciunt cupiditate fuga ipsum est? Eum, minima nesciunt. Maxime non libero enim quam, quod iusto.
            Soluta fugit placeat suscipit ad reiciendis a officiis nemo odit vitae. Eius suscipit similique ea commodi nulla doloremque modi fugit ullam quibusdam ad error exercitationem quidem, optio, laboriosam aliquam recusandae?
            Necessitatibus expedita molestiae nesciunt repellat amet. Ad voluptatibus a inventore quos minus officia! Labore numquam reprehenderit laboriosam vero, mollitia modi itaque veniam doloribus excepturi, aspernatur neque totam, repellat maiores quia.
            Aperiam autem quisquam provident quis alias. Ab quas recusandae at molestiae iure, consequatur itaque necessitatibus, quasi laudantium fuga aut? Expedita doloribus unde animi error officiis dicta vitae libero laboriosam id.
            Corrupti cum reiciendis vitae provident maiores incidunt impedit doloremque suscipit illo eveniet porro eum, animi illum, ut odio et temporibus repellat! Nisi odit reiciendis, sapiente fugit quos recusandae totam laudantium?
            Optio doloribus quod dignissimos odit nulla omnis minima, eligendi impedit officia, obcaecati pariatur fugiat ullam ab culpa voluptatibus quis facilis dolore fugit quisquam eum quidem nesciunt mollitia? Velit, assumenda blanditiis?
            Id, a obcaecati! Reprehenderit, deleniti eligendi dolor quibusdam eos eius, culpa quasi quae totam ad tempore magni. Commodi ut cumque eius aliquid error harum quos non officiis aperiam! Necessitatibus, non.
            Blanditiis ipsum nulla fugit, laudantium iste quidem. Culpa aliquam sunt nostrum obcaecati hic iusto ex enim cupiditate nesciunt ut, tempore, fugiat eos odio porro optio, voluptatum deleniti. Nihil, provident facilis.
            Est vel molestias sint, voluptates explicabo minus maiores esse amet quas fuga perferendis, nesciunt at. Totam qui, obcaecati temporibus impedit eos eligendi sapiente repellat! Alias id quis architecto. Ullam, perspiciatis.
            Nostrum quibusdam hic veritatis odit excepturi delectus autem inventore iusto similique ducimus! Nobis nulla amet natus! Ipsa perspiciatis quaerat, adipisci explicabo saepe ex eligendi quas architecto modi maiores incidunt aut?
            Error debitis provident illum nisi deleniti sit aliquam harum odit quis, ipsum facilis quas facere tempore voluptatum ducimus est corporis non impedit velit. Natus ut omnis commodi ab pariatur possimus!
            Vitae dolor inventore reiciendis blanditiis? Obcaecati amet dolorem illo dolore eaque. Aperiam aspernatur repellendus quas ipsum beatae consequuntur unde enim sequi voluptates aliquid? Voluptas et, facilis doloribus expedita nisi ex.
            Quaerat vel ipsa assumenda quo quam. Qui minima dicta, delectus repellendus iure voluptatem, ullam quaerat eaque quasi, iusto repellat voluptate voluptatibus beatae quas ipsa saepe illo aperiam dignissimos dolorem consequatur?
            Sit iste sed eos possimus assumenda et, cumque nihil voluptatibus vel accusantium expedita, enim debitis natus exercitationem nobis laboriosam facilis neque nesciunt dicta unde inventore similique quis, corrupti ad? Nihil.
            Reiciendis iusto numquam totam fugiat, soluta quae voluptatum architecto at repellat. Omnis, laborum ipsa, modi possimus temporibus dicta, voluptatem voluptas vero unde quaerat maiores ut autem ea non. Laudantium, consequatur!
            Voluptate, voluptates adipisci. Fugit sint saepe soluta, vitae minima veniam repudiandae quis, quibusdam iusto sed assumenda explicabo debitis architecto iure quos aut magni esse sequi exercitationem odio nisi? Cupiditate, impedit.
            Dicta ab illum rem suscipit sequi necessitatibus deserunt mollitia numquam fugit consequatur, deleniti possimus voluptates laboriosam at earum. Cupiditate a doloribus ullam nesciunt asperiores error autem, natus numquam deleniti iusto.
            Maxime ipsam illo laboriosam quis alias reprehenderit, modi sed ad dicta consectetur nemo hic molestias culpa eligendi magni adipisci ut unde, necessitatibus cupiditate corrupti labore veniam doloremque. Ad, error a!
            Possimus mollitia eligendi molestias incidunt, alias necessitatibus laboriosam doloribus libero aliquid nemo obcaecati temporibus quibusdam perspiciatis reiciendis, cum assumenda veniam maiores quo tempora nulla, accusamus voluptatibus! Architecto dolor quibusdam facilis.
            Voluptates dolorum est iste enim veritatis, necessitatibus impedit minus ducimus corrupti ea molestias sequi dolores. Iusto culpa dicta, aperiam quisquam cumque error repellendus impedit ab labore nostrum fugiat. Dolor, ducimus!
            Aliquid, minima eligendi veritatis sapiente praesentium hic dolore soluta incidunt at sequi iusto ducimus sint tempora neque atque quaerat maxime! Voluptas amet earum, odit hic tenetur repellat rerum nesciunt sint.
            Alias at, est nobis omnis praesentium ullam necessitatibus minus nemo. Repellat possimus eveniet rem unde cum necessitatibus a vitae quod neque. Sequi earum officiis cupiditate tenetur quia maxime quaerat natus.
            Voluptate, temporibus deleniti. Eius, incidunt quibusdam accusamus aliquam quo repudiandae veniam. Corporis voluptatem voluptas harum delectus porro minus aliquam officia. Placeat quod fuga inventore officia laudantium harum nihil suscipit et?
            Iste iure laborum magni inventore quasi sequi architecto aspernatur dolore cum ipsam adipisci modi distinctio repellendus facilis, asperiores odio animi qui atque quas dignissimos sed saepe nesciunt! Asperiores, atque blanditiis!
            Dolorem vel sit sed voluptatem ea facilis maxime, quisquam qui veritatis repellat adipisci. Modi, corporis aut. Et, voluptatum esse voluptatem eos magnam dolorum soluta eligendi sint at? Itaque, praesentium sequi!
            Natus tempore consectetur est! Praesentium consequuntur deserunt vitae dolores fugiat! Blanditiis doloribus porro autem, quidem earum consectetur fuga veniam doloremque soluta ducimus minus repudiandae assumenda repellendus aliquam tenetur quisquam! Debitis.
            Minima reiciendis cumque officia repellat, odio consequuntur, non hic quas inventore possimus debitis aliquam illo error aperiam, ut velit ex temporibus. Aliquid sunt, aliquam eligendi nemo neque asperiores? Voluptas, rem!
            Deleniti facere asperiores aliquid eius est harum distinctio nostrum labore cupiditate voluptatum, minus ducimus provident vitae hic rerum nemo quos maiores optio dolores ipsa tempore itaque animi! Ex, assumenda ad.
            Quo, repudiandae a! Obcaecati, quis. Hic dolore veritatis adipisci unde accusantium mollitia, corrupti voluptates repellendus assumenda quasi libero, consequuntur quibusdam delectus nam quod excepturi in a, rerum ullam dicta. Molestias.
            Porro dolores accusamus dignissimos quam voluptate cumque ex suscipit id reiciendis alias? Illum, obcaecati repudiandae. Impedit sint iusto dolore. Earum totam alias odit possimus tempora eum rerum quae accusamus maxime?
            Harum quisquam ut error culpa sequi quis dolore animi reprehenderit totam reiciendis odio tempora quae exercitationem, et fugit, rerum atque, commodi accusamus. Quas labore, iusto cumque quibusdam voluptatum distinctio obcaecati.
            Non a aliquam accusamus! Quod officia quos dolorem provident amet repudiandae libero porro, modi, optio quis molestias repellendus autem qui nesciunt impedit fugit iure totam illo veritatis ducimus temporibus ipsum?
            Fuga voluptate nobis perferendis illo deleniti sed iste nostrum voluptas corrupti? Dicta, aliquam itaque culpa possimus repudiandae quaerat velit sint atque voluptate unde ipsum excepturi nostrum. Consectetur iste reprehenderit animi?
            Fugiat cumque dolore culpa sunt? Voluptatum tenetur corporis necessitatibus quisquam non eos tempora perferendis! Officiis, id, in, sequi odio perferendis facere beatae excepturi sint dolore ipsa assumenda voluptate quos quasi!
            Aperiam, voluptatibus earum quibusdam neque iste consectetur ipsam fugit, voluptas dignissimos assumenda quisquam accusamus soluta et consequatur sequi veritatis sint quaerat obcaecati commodi in iure tempora. Adipisci officia consequatur obcaecati!
            Ullam nesciunt error exercitationem maiores quidem quas fugit voluptate veritatis vitae expedita, culpa quae obcaecati esse sit! Optio cumque, voluptas beatae quod nisi nulla, aspernatur esse molestiae quasi sunt sit!
            Magni et dolorem autem recusandae molestiae reprehenderit ipsum iure, praesentium nihil impedit! Tempora eius, veritatis quibusdam qui laudantium esse ratione laboriosam quos eaque ea. Optio corporis error vitae incidunt enim?
            Magnam, animi sint tempore placeat tenetur cumque quae distinctio quidem consectetur culpa officia labore dolore repudiandae eos voluptates eum ex ea, quam earum? Laborum mollitia quis corrupti voluptatum eligendi. Ex?</h2>
        </div>
        </>
    )
};

export default Footer;
